spring:
  datasource:
    username: admin_telegram
    password: admin
    url: jdbc:postgresql://localhost:5432/DB_telegram
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml
    enabled: true

telegram.bot.token: 7595193557:AAGHOGVzGMeSZHjfjxdQEilg2mCcBqMxQ9M
interval-in-cron: 0 0/1 * * * *
